version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ~/config/mysql/envlist.txt
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    ports:
        - "8080:3306"
