version: '3'

services:
  unifi:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ~/config/mysql/envlist.txt
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    ports:
        - "3306:3306"
