version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ~/config/mysql/envlist.txt
    volumes:
      - ~/contents/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
      - ~/config/mysql/conf.d:/etc/mysql/conf.d
    ports:
        - "3306:3306"
    network_mode: "bridge"
