version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --expire-logs-days=1
    env_file:
      - ~/config/mysql/envlist.txt
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    ports:
        - "8080:3306"
